FROM golang:1.7.4-wheezy

LABEL github.com/akwick/sqinco.version="0.0.1-beta"
LABEL com.example.release-date="2016-12-19"


RUN go get -u -f github.com/stripe/safesql
RUN go get -u -f github.com/GoASTScanner/gas
RUN go get -u -f github.com/stretchr/testify/assert
RUN go get -u -f github.com/akwick/gotcha
RUN go get -u -f github.com/akwick/sqinco


